import Head from "next/head";
import Hero from './components/Hero'
import Projects from './components/Projects'
import About from './components/About'
// import Tools from './components/Tools'
 import Carousel from './components/Carousel'
// import Reviews from './components/Reviews'
// import Contact from './components/Contact'

export default function Home() {
  return (
    <>
      <Head>
        <title>PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={``}>
           <Hero />
           <Projects />
           <About />
           <Carousel />
           {/* <Tools />
           <Reviews />
           <Contact /> */}
        </main>
    </>
  );
}